### ISSUE TITLE
There is an error in the `getDefaultOptions` function: `TypeError: Cannot read properties of undefined (reading 'split')`

### ISSUE THREAD

**Issue by DIYgod** [ANIname/directory-import#17]
This error seems to be caused by the value of `new Error('functional-error').stack`. This is the value I output locally:

```
Error: functional-error
    at getDefaultOptions (/Users/diygod/Code/Project/RSSHub-Hono/node_modules/.pnpm/directory-import@3.1.1/node_modules/directory-import/dist/src/prepare-private-options.js:17:17)
    at preparePrivateOptions (/Users/diygod/Code/Project/RSSHub-Hono/node_modules/.pnpm/directory-import@3.1.1/node_modules/directory-import/dist/src/prepare-private-options.js:31:26)
    at directoryImport (/Users/diygod/Code/Project/RSSHub-Hono/node_modules/.pnpm/directory-import@3.1.1/node_modules/directory-import/dist/src/index.js:15:51)
    at /Users/diygod/Code/Project/RSSHub-Hono/src/routes.ts:3:25
    at Object.<anonymous> (/Users/diygod/Code/Project/RSSHub-Hono/src/routes.ts:3:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Object.j (/Users/diygod/Code/Project/RSSHub-Hono/node_modules/.pnpm/tsx@3.14.0/node_modules/tsx/dist/cjs/index.cjs:1:1197)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
```

It does not contain the string `at file://` inside.

I am using macOS with Node.js v21.6.0 as my environment.

**Comment by KiiDii** [comment]
Hi. Could you please give me your code to call the module (along with the input data)? I will try to reproduce the problem to solve it

**Comment by DIYgod** [comment]
I further discovered that it only occurs when running through tsx, this is the minimum reproducible code I submitted:

https://github.com/DIYgodLab/directory-import-demo

**Comment by KiiDii** [comment]
<img width="1680" alt="image" src="https://github.com/ANIname/directory-import/assets/23314538/a8187fbb-7d31-45ea-893c-461c987b24f0">

**Comment by DIYgod** [comment]
`directory-import@3.2.1` works for me, thank you very much.
